# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=200, null=True, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('loan_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('email_validation_status', models.BooleanField(default=True)),
                ('approval_status', models.BooleanField(default=False)),
            ],
        ),
    ]
