# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='email_validation_status',
        ),
    ]
